!*******************************************************************************
!*** DROPlet Simulation (DropS)
!*** BY NIKOLAOS CHAMAKOS (nikoscham@gmail.com)
!*** NATIONAL TECHNICAL UNIVERSITY OF ATHENS, GREECE
!*******************************************************************************

MODULE CommonVars

!*******************************************************************************
!*** DESCRIPTION: COMMON VARIABLES
!*******************************************************************************
  
IMPLICIT NONE

!*** SOURCE DIRECTORY
CHARACTER(LEN=255)::SrcDir
!*** RESULTS DIRECTORY
CHARACTER(LEN=255)::ResDir
!*** PARENT DIRECTORY
CHARACTER(LEN=255)::Dir
!*** SOLVER MODE
INTEGER(KIND=8)::SolverID
!*** COUNTER (NEWTON-RAPHSON ITERATIONS)
INTEGER(KIND=8)::NRcnt
!*** COUNTER (DECOUPLED ITERATIONS)
INTEGER(KIND=8)::DCPcnt
!*** ELEMENTS TYPE (AUGMENTED YOUNG-LAPLACE EQUATION (AYL))
INTEGER(KIND=8)::eltypeYL
!*** ELEMENTS TYPE (ELECTRIC FIELD DISTRIBUTION EQUATIONS (EL))
INTEGER(KIND=8)::eltypeEL
!*** ELEMENTS TYPE (EIKONAL EQUATION (EI))
INTEGER(KIND=8)::eltypeEI
!*** ELEMENTS TYPE (ADAPTIVE MESH EQUATION(ADA))
INTEGER(KIND=8)::eltypeADA
!*** NUMBER OF UNKNOWNS AT EACH ELEMENT (AYL EQUATION)
INTEGER(KIND=8)::nelnodesYL
!*** NUMBER OF UNKNOWNS AT EACH ELEMENT (EL EQUATIONS)
INTEGER(KIND=8)::nelnodesEL
!*** NUMBER OF UNKNOWNS AT EACH ELEMENT (EI EQUATION)
INTEGER(KIND=8)::nelnodesEI
!*** NUMBER OF UNKNOWNS AT EACH ELEMENT (ADA EQUATION)
INTEGER(KIND=8)::nelnodesADA
!*** LAST MARKED ELEMENT AT EIKONAL SEARCH
INTEGER(KIND=8)::lastelEI
!*** GEOMETRY MIRROR FUNCTION FOR EIKONAL EQUATION
INTEGER(KIND=8)::geommirEI
!*** DROPLET SURFACE NODES (EL EQUATIONS)
INTEGER(KIND=8)::dropPointsfl
!*** SURROUNDING MEDIUM ELEMENTS (EL EQUATIONS)
INTEGER(KIND=8)::AirSurffl
!*** SOLID DIELECTRIC ELEMENTS (EL EQUATIONS)
INTEGER(KIND=8)::DielSurffl
!*** DROPLET SURFACE NODES (EL EQUATIONS)
INTEGER(KIND=8)::DropLinefl
!*** ELECTRODE SURFACE NODES (EL EQUATIONS)
INTEGER(KIND=8)::DielLinefl
!*** SOLID BOUNDARY NODES (EI EQUATION)
INTEGER(KIND=8)::SolidLinefl
!*** UPPER BOUNDARY NODES (EI EQUATION)
INTEGER(KIND=8)::UpperLinefl
!*** GAUSS POINTS (EL EQUATIONS)
INTEGER(KIND=8)::NumgpsEL
!*** GAUSS POINTS (EI EQUATION)
INTEGER(KIND=8)::NumgpsEI
!*** SOLVER GENARATOR SOFTWARE
INTEGER(KIND=8)::meshGen
!*** NUMBER OF NODES (AYL EQUATION)
INTEGER(KIND=8)::nnodesYL
!*** NUMBER OF NODES (AYL INITIAL SOLUTION)
INTEGER(KIND=8)::nnodesuoYL
!*** NUMBER OF NODES (EL EQUATIONS)
INTEGER(KIND=8)::nnodesEL
!*** NUMBER OF NODES (EI EQUATION)
INTEGER(KIND=8)::nnodesEI
!*** NUMBER OF NODES (ADA EQUATION)
INTEGER(KIND=8)::nnodesADA
!*** ELEMENTS COUNTER
INTEGER(KIND=8)::nell
!*** NUMBER OF ENTRIES OF THE JABOBIAN MATRIX
INTEGER(KIND=8)::AMcnt
!*** NUMBER OF ELEMENTS (AYL INITIAL SOLUTION)
INTEGER(KIND=8)::nelluoYL
!*** NUMBER OF ELEMENTS (AYL EQUATION)
INTEGER(KIND=8)::nellYL
!*** NUMBER OF ELEMENTS (EL EQUATIONS)
INTEGER(KIND=8)::nellEL
!*** NUMBER OF ELEMENTS (EI EQUATION)
INTEGER(KIND=8)::nellEI
!*** NUMBER OF ELEMENTS (ADA EQUATION)
INTEGER(KIND=8)::nellADA
!*** NUMBER OF TOTAL UNKNOWNS
INTEGER(KIND=8)::noukLS
!*** NUMBER OF UNKNOWNS (AYL INITIAL SOLUTION)
INTEGER(KIND=8)::noukuoYL
!*** NUMBER OF UNKNOWNS (AYL EQUATION)
INTEGER(KIND=8)::noukYL
!*** NUMBER OF UNKNOWNS (EL EQUATIONS)
INTEGER(KIND=8)::noukEL
!*** NUMBER OF UNKNOWNS (EI EQUATION)
INTEGER(KIND=8)::noukEI
!*** NUMBER OF UNKNOWNS (ADA EQUATION)
INTEGER(KIND=8)::noukADA
!*** NUMBER OF PILLARS
INTEGER(KIND=8)::nopillars
!*** NUMBER OF EXTERNAL ITERATIONS (EI EQUATION)
INTEGER(KIND=8)::ExtItEI
!*** PRINT JACOBIAN MATRIX
INTEGER(KIND=8)::printPrecond
!*** FLAT SOLID SURFACE AT THE BOTTOM OF THE DIELECTRIC
INTEGER(KIND=8)::flatSolidDown
!*** FLAT SOLID SURFACE AT THE TOP OF THE DIELECTRIC
INTEGER(KIND=8)::flatSolidUp
!*** ADAPTIVE MESH REFINEMENT
INTEGER(KIND=8)::AdaMesh
!*** DISJOINING PRESSURE EXPONENT C1 (AYL EQUATION)
INTEGER(KIND=8)::C1YL
!*** DISJOINING PRESSURE EXPONENT C2 (AYL EQUATION)
INTEGER(KIND=8)::C2YL
!*** DISJOINING PRESSURE EXPONENT C3 (AYL EQUATION)
INTEGER(KIND=8)::C3YL
!*** PSEUDO-TRANSIENT CONTINUATION
INTEGER(KIND=8)::TraCon
!*** JACOBIAN MATRIX PATTERN INPUT
INTEGER(KIND=8)::JacobMatP
!*** TOTAL NUMBER OF NEIGHBORING ELEMENTS (AYL EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::kindYL
!*** TOTAL NUMBER OF NEIGHBORING ELEMENTS (EL EQUATIONS)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::kindEL
!*** TOTAL NUMBER OF NEIGHBORING ELEMENTS (EI EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::kindEI
!*** TOTAL NUMBER OF NEIGHBORING ELEMENTS (ADA EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::kindADA
!*** DIRICHLET BOUNDARY CONDITION (EL EQUATIONS)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::ncodEL
!*** DIRICHLET BOUNDARY CONDITION (EI EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::ncodEI
!*** DIRICHLET BOUNDARY CONDITION (ADA EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::ncodADA
!*** ELEMENTS POINTER (EL EQUATIONS)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::nellidEL
!*** ELEMENTS POINTER (EI EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::nellidEI
!*** NEIGH(NODE,#NTH)=#NTH NEIGHBORING ELEMENT (AYL EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::neighYL
!*** NEIGH(NODE,#NTH)=#NTH NEIGHBORING ELEMENT (EL EQUATIONS)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::neighEL
!*** NEIGH(NODE,#NTH)=#NTH NEIGHBORING ELEMENT (EI EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::neighEI
!*** NEIGH(NODE,#NTH)=#NTH NEIGHBORING ELEMENT (ADA EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::neighADA
!*** NOP ARRAY (CORRELATION BETWEEN GLOBAL & LOCAL NODES NUMBERING
!*** FOR AYL EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::nopYL
!*** NOP ARRAY (EL EQUATIONS)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::nopEL
!*** NOP ARRAY (EI EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::nopEI
!*** NOP ARRAY (ADA EQUATION)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:,:)::nopADA
!*** JACOBIAN MATRIX ENTRIES COUNTER
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::am2
!*** NUMBER OF NODES AT THE DROPLET SURFACE 
!*** (YLnodes MAY BE DIFFERENT FROM nnodesYL)
INTEGER(KIND=8),ALLOCATABLE,DIMENSION(:)::YLnodes
!*** PI CONSTANT
DOUBLE PRECISION::Pi
!*** CHARACTERISTIC LENGTH
DOUBLE PRECISION::roYL
!*** DROPLET VOLUME
DOUBLE PRECISION::voYL
!*** INTERFACIAL TENSION
DOUBLE PRECISION::stYL
!*** GRAVITATIONAL ACCELERATION (m/s^2)
DOUBLE PRECISION::gYL
!*** LIQUID DENSITY (Kg/m^3)
DOUBLE PRECISION::denYL
!*** ELECTRIC CONSTANT (VACUUM PERMITIVITY)
DOUBLE PRECISION::eoEL
!*** SOLID MATERIAL DIELECTRIC CONSTANT
DOUBLE PRECISION::edEL
!*** SURROUNDING MEDIUM DIELECTRIC CONSTANT
DOUBLE PRECISION::esEL
!*** SOLID-LIQUID INTERACTION CONSTANT
DOUBLE PRECISION::sigmaYL
!*** SOLID-LIQUID INTERACTION CONSTANT
DOUBLE PRECISION::SmallNumbYL
!*** GRAVITY EFFECT
DOUBLE PRECISION::GcYL
!*** REPETITION PERIOD OF THE SOLID SURFACE
DOUBLE PRECISION::scycleEI
!*** HEIGH LIMIT OF EIKONAL EQUATION
DOUBLE PRECISION::HeighLimitYL
!*** WETTING PARAMETER
DOUBLE PRECISION::WParamYL
!*** NEWTON ITERATIONS TOLERANCE
DOUBLE PRECISION::PPres
!*** MAXIMUM WIDTH OF THE 2D DOMAIN (EL EQUATIONS)
DOUBLE PRECISION::xlimitEL
!*** MAXIMUM HEIGHT OF THE 2D DOMAIN (EL EQUATIONS)
DOUBLE PRECISION::ylimitEL
!*** MINIMUM X COORDINATE OF THE 2D DOMAIN (EI EQUATION)
DOUBLE PRECISION::xfirstEI
!*** MAXIMUM WIDTH OF THE 2D DOMAIN (EI EQUATION)
DOUBLE PRECISION::xlimitEI
!*** MAXIMUM HEIGHT OF THE 2D DOMAIN (EI EQUATION)
DOUBLE PRECISION::ylimitEI
!*** DIELECTRIC THICKNESS
DOUBLE PRECISION::DielThickEL
!*** APPLIED VOLTAGE
DOUBLE PRECISION::VltEL
!*** MAXIMUM APPLIED VOLTAGE
DOUBLE PRECISION::VltMaxEL
!*** MAXIMUM WETTING PARAMETER
DOUBLE PRECISION::WParamMaxYL
!*** WETTING PARAMETER STEP
DOUBLE PRECISION::WParamStepYL
!*** APPLIED VOLTAGE STEP
DOUBLE PRECISION::VltStepEL
!*** DS STEP FOR PREUDO ARC-LENGTH CONTINUATION
DOUBLE PRECISION::dsc
!*** ELEMENT SIZE FOR DENSE REGION (EL DOMAIN)
DOUBLE PRECISION::hdensEL
!*** ELEMENT SIZE FOR DENSE REGION (EI DOMAIN)
DOUBLE PRECISION::hdensEI
!*** ELEMENT SIZE FOR SPARSE REGION (EL DOMAIN)
DOUBLE PRECISION::ldensEL
!*** ELEMENT SIZE FOR SPARSE REGION (EI DOMAIN)
DOUBLE PRECISION::ldensEI
!*** MESH GROWTH RATE
DOUBLE PRECISION::GrateEL
!*** VISCOUS TERM FOR THE SOLUTION OF THE EI EQUATION
DOUBLE PRECISION::ViscTermEI
!*** EFFECTIVE VISCOUS TERM FOR THE SOLUTION OF THE EI EQUATION
DOUBLE PRECISION::effViscTermEI
!*** GAUSS POINTS (EL EQUATIONS)
DOUBLE PRECISION::gpEL(3)
!*** GAUSS WEIGHTS (EL EQUATIONS)
DOUBLE PRECISION::wgpEL(3)
!*** GAUSS POINTS (EI EQUATION)
DOUBLE PRECISION::gpEI(3)
!*** GAUSS WEIGHTS (EI EQUATION)
DOUBLE PRECISION::wgpEI(3)
!*** PILLAR WIDTH
DOUBLE PRECISION::wpillar
!*** DISTANCE BETWEEN PILLARS
DOUBLE PRECISION::dpillar
!*** PILLAR HEIGHT
DOUBLE PRECISION::hpillar
!*** PILLAR SMOOTHNESS
DOUBLE PRECISION::smpillar
!*** EIKONAL EQUATION FLAG
DOUBLE PRECISION::actFlagEI
!*** MINIMUM DROPLET HEIGHT
DOUBLE PRECISION::MinDropletHeight
!*** DROPLET VOLUME MULTIPLIER
DOUBLE PRECISION::cVol
!*** DISJOINING PRESSURE PRECURSOR FILM PARAMETER  (AYL EQUATION)
DOUBLE PRECISION::flmYL
!*** TIME STEP FOR PSEUDO-TRANSIENT CONTINUATION
DOUBLE PRECISION::TStep
!*** MAXIMUM TIME STEP FOR PSEUDO-TRANSIENT CONTINUATION
DOUBLE PRECISION::TStepMax
!*** YOUNG'S CONTACT ANGLE
DOUBLE PRECISION::thYoungYL
!*** X (UNKNOWN) VECTOR
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::xvec
!*** GALERKIN RESIDUALS VECTOR
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::res
!*** GALERKIN RESIDUALS DERIVATIVE (FOR THE COMPUTATION OF dUdS)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::dresdp
!*** JACOBIAN MATRIX (COORDINATES FORMAT)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::am1
!*** AYL EQUATION SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uYL
!*** ADA EQUATION SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uADA
!*** AYL EQUATION INITIAL SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uYLFirst
!*** AYL EQUATION INITIAL SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uYLSecond
!*** AYL EQUATION INITIAL SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uoYL
!*** AYL EQUATION INITIAL SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uminus1YL
!*** EL EQUATIONS SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uEL
!*** EI EQUATION SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::uEI
!*** ARC-LENGTH COORDINATES FOR THE AYL EQUATION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::sptYL
!*** ARC-LENGTH COORDINATES FOR THE AYL EQUATION INITIAL SOLUTION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::sptuoYL
!*** ARC-LENGTH COORDINATES DERIVATIVES FOR THE AYL EQUATION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::dsptYL
!*** POLAR COORDINATES FOR THE CYL EQUATION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::thptYL
!*** POLAR COORDINATES DERIVATIVES FOR THE CYL EQUATION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::dthptYL
!*** C COORDINATES FOR THE ADA EQUATION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::cptADA
!*** C COORDINATES DERIVATIVES FOR THE ADA EQUATION
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::dcptADA
!*** X COORDINATES DERIVATIVES (EL EQUATIONS)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::xptEL
!*** Y COORDINATES DERIVATIVES (EL EQUATIONS)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::yptEL
!*** X COORDINATES DERIVATIVES (EI EQUATION)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::xptEI
!*** Y COORDINATES DERIVATIVES (EI EQUATION)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::yptEI
!*** X COORDINATES FOR THE AYL GAUSS POINTS
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::xptYLGP
!*** Y COORDINATES FOR THE AYL GAUSS POINTS
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::yptYLGP
!*** ARC-LENGTH COORDINATES FOR THE AYL GAUSS POINTS
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::sptYLGP
!*** DIRICHLET BOUNDARY CONDITION VALUE (EL EQUATIONS)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::bcEL
!*** DIRICHLET BOUNDARY CONDITION VALUE (EI EQUATION)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::bcEI
!*** DIRICHLET BOUNDARY CONDITION VALUE (ADA EQUATION)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::bcADA
!*** (ELECTRIC FIELD NORM)^2 AT THE AYL GAUSS POINTS
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::efieldYLGP
!*** ELECTRIC FIELD NORM CALCULATED AT THE CENTRE OF THE ELEMENTS 
!*** (EL EQUATIONS)
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::efieldELElm
!*** DERIVATIVE OF THE SOLUTION WITH RESPECT TO 
!*** THE PREUDO ARC-LENGTH CONTINUATION PARAMETER
DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:)::dUdS

END MODULE

!*******************************************************************************
