!*******************************************************************************
!*** DROPlet Simulation (DropS)
!*** BY NIKOLAOS CHAMAKOS (nikoscham@gmail.com)
!*** NATIONAL TECHNICAL UNIVERSITY OF ATHENS, GREECE
!*******************************************************************************

PROGRAM DropS

!*******************************************************************************
!*** DESCRIPTION: CODE FOR PREDICTING THE EQUILIBRIUM SHAPE OF A DROPLET ON A
!*** STRUCTURED SUBSTRATE. IT SOLVES THE YOUNG-LAPLACE EQUATION OF CAPILLARY
!*** HYDROSTATICS AUGMENTED WITH A DISJOINING PRESSURE TERM WHICH MODELS THE
!*** SOLID-LIQUID INTERACTIONS. IN THIS APPROACH, THE LIQUID-SOLID AND THE
!*** LIQUID-VAPOR INTERFACES ARE TREATED IN A UNIFIED FRAMEWORK (ONE EQUATION
!*** FOR BOTH INTERFACES), THUS IT IS PARTICULARLY EFFECTIVE FOR
!*** MODELING CASES WHERE THE NUMBER OF CONTACT LINE IS A PRIORY UNKNOWN.
!*******************************************************************************
!*** DOCUMENTATION (IN PEER-REVIEWED JOURNALS)
!*** 1) CHAMAKOS, KAVOUSANAKIS, PAPATHANASIOU, SOFT MATTER (2013)
!*** 2) CHAMAKOS, KAVOUSANAKIS, PAPATHANASIOU, LANGMUIR (2014)
!*** 3) KAVOUSANAKIS, CHAMAKOS, PAPATHANASIOU, J. PHYS. CHEM. C (2015)
!*******************************************************************************

USE CommonVars
USE defpar
IMPLICIT NONE
DOUBLE PRECISION::StartTime
DOUBLE PRECISION::FinishTime

!*** INITIALIZE DropS
CALL CPU_TIME(StartTime)
WRITE(*,'(a)')'** DropS **'
CALL GETCWD(SrcDir)
CALL CHDIR("..")
CALL GETCWD(Dir)
!*** GLOBAL PARAMETERS
CALL defparam
WRITE(ResDir,*)TRIM(Dir),'/Results'
CALL CHDIR(ADJUSTL(ResDir))

!*** SOLVER SELECTION
SELECT CASE (SolverID)
  CASE(1)
!*** EIKONAL EQUATION SOLVER
    CALL EISolver
  CASE(2)
!*** AUGMENTED YOUNG-LAPLACE EQUATION SOLVER (ZERO-ORDER CONTINUATION)
    VltEL=0.d0; CALL YLSolver
  CASE(3)
!*** AUGMENTED YOUNG-LAPLACE EQUATION SOLVER (PSEUDO ARC-LENGTH CONTINUATION)
    VltEL=0.d0; CALL YLParamSolver
  CASE(4)
!*** DECOUPLED ELECTROWETTING SOLVER (ZERO-ORDER CONTINUATION)
    CALL EWSolver
  CASE(5)
!*** DECOUPLED ELECTROWETTING SOLVER (PSEUDO ARC-LENGTH CONTINUATION)
    CALL EWParamSolver
  CASE(6)
!*** TIME STEP ELECTROWETTING SOLVER
    CALL EWSolver
  CASE(7)
!*** TIME STEP AUGMENTED YOUNG-LAPLACE EQUATION SOLVER
    VltEL=0.d0; CALL YLSolver
  CASE(8)
!*** CONVENTIONAL YOUNG-LAPLACE EQUATION SOLVER
    CALL CYLSolver
END SELECT

!*** TERMINATE DropS
CALL CHDIR(SrcDir)
CALL CPU_TIME(FinishTime)
WRITE(*,'(a,f14.4,1x,a,/)')'SOLUTION TIME:',FinishTime-StartTime,'s'

END PROGRAM

!*******************************************************************************
